# Generated by Django 3.0.7 on 2020-07-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerJobBuyerA00',
            fields=[
                ('job_buyer_a00_rec', models.AutoField(primary_key=True, serialize=False)),
                ('job_buyer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=11)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
                ('owner_contact_id_id', models.IntegerField()),
            ],
            options={
                'db_table': 'buyer_job_buyer_a00',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerJobBuyerA01',
            fields=[
                ('job_buyer_a01_rec', models.AutoField(primary_key=True, serialize=False)),
                ('job_skills_id', models.CharField(max_length=50)),
                ('skill_id', models.IntegerField()),
                ('skill_description', models.CharField(max_length=14)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'buyer_job_buyer_a01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerJobBuyerA02',
            fields=[
                ('job_buyer_a02_rec', models.AutoField(primary_key=True, serialize=False)),
                ('bid_invite_id', models.CharField(max_length=50)),
                ('group_id_id', models.IntegerField()),
                ('status', models.CharField(max_length=11)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'buyer_job_buyer_a02',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerJobBuyerA03',
            fields=[
                ('job_buyer_a03_rec', models.AutoField(primary_key=True, serialize=False)),
                ('bid_id', models.CharField(max_length=50)),
                ('bidder_reference_id', models.CharField(db_column='bidder_reference_Id', max_length=50)),
                ('group_id_id', models.IntegerField()),
                ('job_skills_id', models.CharField(max_length=50)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=11)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'buyer_job_buyer_a03',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobJobA00',
            fields=[
                ('job_a00_rec', models.AutoField(primary_key=True, serialize=False)),
                ('awarded_job_id', models.CharField(max_length=50)),
                ('group_id_id', models.IntegerField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=9)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'job_job_a00',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobJobA01',
            fields=[
                ('job_a01_rec', models.AutoField(primary_key=True, serialize=False)),
                ('milestone_id', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=9)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'job_job_a01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderJobProviderA00',
            fields=[
                ('job_provider_a00_rec', models.AutoField(primary_key=True, serialize=False)),
                ('job_provider_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_id_id', models.IntegerField()),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'provider_job_provider_a00',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderJobProviderA01',
            fields=[
                ('job_provider_a01_rec', models.AutoField(primary_key=True, serialize=False)),
                ('job_bid_reference_id', models.CharField(max_length=50)),
                ('datetimestamp', models.DateTimeField()),
                ('group_id', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('active_status', models.BooleanField()),
            ],
            options={
                'db_table': 'provider_job_provider_a01',
                'managed': False,
            },
        ),
    ]
