# Generated by Django 2.2 on 2019-08-27 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_auto_20190825_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_accreditations', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=150)),
                ('points', models.FloatField()),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.Division')),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=150)),
                ('subpoints', models.FloatField()),
                ('remarks', models.CharField(max_length=150)),
                ('subtotal', models.FloatField()),
                ('subdivision', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.Subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.College')),
                ('created_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Program')),
                ('type_of_accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.AccreditationType')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.Forms'),
        ),
    ]
