# Generated by Django 2.2 on 2019-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
