# Generated by Django 2.2 on 2019-08-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='accreditation_type',
        ),
    ]
