# Generated by Django 2.2 on 2019-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='criteria',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
