# Generated by Django 2.2 on 2019-07-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoE_IT_FORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='TIP', max_length=100)),
                ('branch', models.CharField(default='MANILA', max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('program_chair', models.CharField(max_length=100)),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='deanforms',
            name='dean',
        ),
        migrations.DeleteModel(
            name='ChairpersonForms',
        ),
        migrations.DeleteModel(
            name='DeanForms',
        ),
    ]
