# Generated by Django 2.2 on 2019-08-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditationtype',
            old_name='type_of_accreditation',
            new_name='type_of_accreditations',
        ),
    ]
