# Generated by Django 2.2 on 2019-07-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20190722_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='coe_it_form',
            name='curriculum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='faculty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='graduate_profile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='graduate_programs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='graduate_tracker',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='it_capability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='laboratory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='libraries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='program_admin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coe_it_form',
            name='student_report',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
