# Generated by Django 2.2 on 2019-08-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20190822_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.College'),
        ),
    ]
