# Generated by Django 2.2 on 2019-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_forms_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
