# Generated by Django 2.2 on 2019-08-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20190813_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='created_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
