# Generated by Django 2.2 on 2019-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_division_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='_total',
            field=models.FloatField(db_column='total', default=0),
        ),
    ]
