# Generated by Django 2.2 on 2019-08-03 16:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190804_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='subdivision_detail',
        ),
        migrations.AddField(
            model_name='forms',
            name='subdivision_detail',
            field=multiselectfield.db.fields.MultiSelectField(default=1, max_length=200, verbose_name='SubdivisionDetail'),
            preserve_default=False,
        ),
    ]
