# Generated by Django 2.2.4 on 2019-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190814_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
