# Generated by Django 2.2.4 on 2019-08-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_subdivision_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
