# Generated by Django 2.2 on 2019-08-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20190804_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='subdivision_detail',
        ),
        migrations.AddField(
            model_name='forms',
            name='subdivision_detail',
            field=models.ManyToManyField(to='forms.SubdivisionDetail'),
        ),
    ]
