# Generated by Django 2.1.3 on 2019-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
