# Generated by Django 2.2 on 2019-08-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_subdivision__total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='total',
            new_name='_total',
        ),
    ]
