# Generated by Django 2.2 on 2019-08-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190804_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivisiondetail',
            name='accreditation_type',
        ),
        migrations.RemoveField(
            model_name='subdivisiondetail',
            name='basic_info',
        ),
        migrations.RemoveField(
            model_name='subdivisiondetail',
            name='division',
        ),
        migrations.RemoveField(
            model_name='subdivisiondetail',
            name='subdivision',
        ),
    ]
