# Generated by Django 2.2 on 2019-09-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190901_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='year',
            field=models.IntegerField(),
        ),
    ]
