# Generated by Django 2.2.4 on 2019-08-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190817_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivisiondetail',
            name='points',
        ),
    ]
