# Generated by Django 2.2 on 2019-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190827_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='_total',
            field=models.FloatField(db_column='total', default=0),
        ),
    ]
