# Generated by Django 2.2 on 2019-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20190827_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='_total',
        ),
        migrations.AddField(
            model_name='subdivision',
            name='total',
            field=models.FloatField(db_column='get_total', default=0),
        ),
    ]
