# Generated by Django 2.2 on 2019-09-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20190905_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accreditation_image'),
        ),
    ]
