# Generated by Django 2.2 on 2019-09-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_accreditationtype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='pdf',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='files',
            name='author',
        ),
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
        migrations.AddField(
            model_name='files',
            name='subdivisiondetail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forms.SubdivisionDetail'),
            preserve_default=False,
        ),
    ]
