# Generated by Django 2.2 on 2019-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20190827_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='total',
        ),
        migrations.AddField(
            model_name='subdivision',
            name='_total',
            field=models.FloatField(db_column='total', default=0),
        ),
    ]
