# Generated by Django 2.2 on 2019-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_subdivisiondetail_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
