# Generated by Django 2.2 on 2019-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20190827_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='_total',
            field=models.FloatField(db_column='totals', default=0),
        ),
    ]
