# Generated by Django 2.2 on 2019-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20190827_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='_total',
            field=models.FloatField(db_column='total', default=0),
        ),
    ]
