# Generated by Django 2.2 on 2019-09-22 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20190922_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='_total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='forms',
            name='_percent',
            field=models.DecimalField(db_column='percent', decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='forms',
            name='_total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='_total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='subdivisiondetail',
            name='subpoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='subdivisiondetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
