# Generated by Django 2.2 on 2019-09-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20190922_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
