# Generated by Django 2.2 on 2019-10-03 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('forms', '0013_forms_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivisiondetail',
            name='can_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Program'),
        ),
    ]
