# Generated by Django 2.2 on 2019-10-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_subdivisiondetail_can_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
