# Generated by Django 2.2 on 2019-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20191003_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='note_from_audited',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='note_from_auditor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
