# Generated by Django 2.2 on 2019-10-04 23:26

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20191003_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, max_length=10000, null=True, upload_to=forms.models.Files.uploads),
        ),
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=1500),
        ),
    ]
