# Generated by Django 2.2 on 2019-10-06 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20191006_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivisiondetail',
            name='_subpoints',
        ),
        migrations.AddField(
            model_name='subdivisiondetail',
            name='subpoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
