# Generated by Django 2.2 on 2019-10-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20191006_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_note', models.TextField()),
                ('own_note', models.TextField()),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Files')),
            ],
        ),
    ]
