# Generated by Django 2.2 on 2019-10-08 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_auto_20191008_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivisiondetail',
            name='subpoints',
            field=models.DecimalField(db_column='max_subpoints', decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
