# Generated by Django 2.2 on 2019-10-09 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0029_auto_20191008_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='files',
            name='note_from_audited',
        ),
        migrations.RemoveField(
            model_name='files',
            name='note_from_auditor',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='comment',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Files'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
