# Generated by Django 2.2 on 2019-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_auto_20191010_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
