# Generated by Django 3.0.7 on 2020-06-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContactA04',
            fields=[
                ('contact_a04_rec', models.AutoField(primary_key=True, serialize=False)),
                ('contact_deduction_id', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('active_status', models.BooleanField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('deduction_id_id', models.IntegerField()),
            ],
            options={
                'db_table': 'contact_contact_a04',
                'managed': False,
            },
        ),
    ]
