# Generated by Django 2.2 on 2019-10-04 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='middle_initial',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')]),
        ),
    ]
