# Generated by Django 2.2 on 2019-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_VPAA',
            field=models.BooleanField(default=False),
        ),
    ]
