# Generated by Django 2.2 on 2019-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
