# Generated by Django 2.2 on 2019-07-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_myuser_is_vpaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_DC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_DEAN',
            field=models.BooleanField(default=False),
        ),
    ]
