# Generated by Django 2.2 on 2019-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
