# Generated by Django 2.2 on 2019-07-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190717_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_DC',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_DEAN',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_VPAA',
        ),
    ]
