# Generated by Django 2.2 on 2019-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190717_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='college',
            field=models.CharField(choices=[('CITE', 'College of Information Technology Education'), ('CEA', 'College of Engineering and Arcchitecture'), ('CBE', 'College of Business Eduction'), ('COA', 'College of Arts')], max_length=50, null=True),
        ),
    ]
