# Generated by Django 2.2 on 2019-08-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190812_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.College'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Role'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
