# Generated by Django 2.2 on 2019-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_myuser_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='program',
            field=models.CharField(choices=[('BSCS', 'Bachelor of Science in Computer Science'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BSEMC', 'Bachelor of Science in Entertainment Multimedia Education'), ('BSCE', 'Bachelor of Science in Civil Engineering'), ('BSIE', 'Bachelor of Science in Industrial Engineering'), ('N/A', 'Not Applicable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='college',
            field=models.CharField(choices=[('CITE', 'College of Information Technology Education'), ('CEA', 'College of Engineering and Architecture'), ('CBE', 'College of Business Eduction'), ('COA', 'College of Arts'), ('N/A', 'Not Applicable')], max_length=50, null=True),
        ),
    ]
