# Generated by Django 2.2 on 2019-08-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20190813_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='role',
        ),
    ]
